### ISSUE TITLE
Ch 33 - it would be worth mentioning the precision of the numbers in the matrix.

### ISSUE THREAD

**Issue by sebjameswml** [Pomax/BezierInfo-2#245]
I implemented a Bezier fitting algorithm following Ch 33. For a little while I was finding it hard to figure out why I was seeing good fits for Bezier curves of order 5 and below and poor fits above that. It just wasn't quite as good as your javascript example. The issue was that I had used single precision floating point numbers in my matrix algebra; so it turns out that you get much better results with double precision numbers.

**Comment by sebjameswml** [comment]
The reason I thought it could be mentioned at some point is because there's a clear issue for this particular process of fitting a high order Bezier curve to a set of points and the text states that the process should work up to around 10th order curves (which it does, with high precision numerics). I implemented it correctly, with single precision maths and got a different result. Before I realised it was just the precision, I assumed that, as usual, I had made some other sort of error. You could simply add in parentheses that (it'll work to about 5th order with single precision maths), or (be sure to use double precision numbers). Perhaps after mentioning early on, as you suggest, that precision is something to be aware of for some of the techniques in the article.

As to the implication that everyone uses double/max precision: I don't! in fact, I always start with single precision, because programs often run faster that way, and then revert to double precision if there's an issue (so I should have figured this one out in less than the hour or so it took!). Many of the other processes in the primer work just fine with single precision maths; computing a curve given the control points, for example. However, I've not examined all of them.

Anyway, Thanks for writing the article - it's really great! If you want to take a look at my code, it's in https://github.com/ABRG-Models/morphologica/tree/BezierUpdates  (still work in progress; I'm just adding curve derivatives and I will probably templatize my BezCurve class to make it easy to switch between precisions).

**Comment by Pomax** [comment]
On a sidenote: I can't think of a single instance where higher order Beziers actually make sense - what are you doing that requires 10th (or higher) order curves?

**Comment by sebjameswml** [comment]
Ah, that depends what you're doing with the curves.  I'm tracing around images of brain slices. These fitted curves are great to allow a user to click points on the boundary of the brain and get a well-fit curve. I'm still going to need to stitch several curves together though, so you could argue that I might as well just stitch together a larger number of 3rd order Bezier curves rather than a couple of 8th or 9th order curves.

**Comment by Pomax** [comment]
hm, yeah I'd have gone with tesselated cubics for that usecase (mostly because they're much easier to post-edit). Unfortunately, the section on shape tracing is still not written... but it'd be similar to how potrace does its job.

**Comment by sebjameswml** [comment]
Thanks for the tip about potrace, that's useful.

**Comment by Pomax** [comment]
closing this issue, as it feels out of scope, even if it's sort of related.
